In [25]:
import os
import numpy as np
import cv2 as cam
import pandas as pd
import warnings


In [26]:
Neural_network_folder = os.listdir("/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK")

# THis function down below clear the .DS_Store file which is specific to mac_os   
# wherever this function is called, it is just to remove that .DS_Store file of mac
def list_clean(L):
    for i in L:
        if i ==".DS_Store":
            L.remove(i)

list_clean(Neural_network_folder)

#This code below is supposed to get the names of the folder inside the neural_network/ folder
Names_folder = os.listdir(f"/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Train")
list_clean(Names_folder)

images_path = [] # as the name suggests, it stores the path of each of the image and stuff
images = []# to store each of the image information of all the folders ....

for i in Names_folder:
    list_clean(images_path)
    images_path= os.listdir(f"/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Train/{i}")
    
    #Loop for storing the image info into the image_James List
    for j in images_path:
        img = cam.imread(f"/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Train/{i}/{j}",cam.IMREAD_GRAYSCALE)
        images.append(img.flatten())
    


# convert the list into array for vector operations
images = np.array(images)


Names_folder

['James', 'Joel', 'Jovi', 'Jane', 'Jade']

In [27]:
images = pd.DataFrame(images)
images = np.array(images)  #experimentation, nevermind this

In [28]:
images = images/255 #this is to scale down the images and the info more centered
images = images.T
images

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00784314, 0.00784314, 0.00784314, ..., 0.00784314, 0.00784314,
        0.00784314],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(784, 4000))

In [29]:
#this randomly initializes the weights and bias for the beginning the whole thing
def weight_bias_make(no_of_neurons,inputs,number):
    return np.random.randn(no_of_neurons,inputs)*0.01, 0
#this is for getting answers before getting into the next layer by dot product
def forward_prop(weights,input_data,bias):
    return np.dot(weights,input_data) + bias

def activation_function(Z):
    #this is the activation function to get the values squished
    return (1/(1+ np.exp(-Z)))
def relu(x):
    return np.maximum(0, x)

def softmax(x):
    # shift input for numerical stability
    x_shifted = x - np.max(x, axis=0, keepdims=True)
    
    # sompute the exponentials
    exp_x = np.exp(x_shifted)
    
    # normalize by the sum of exponentials for each column
    softmax_probs = exp_x / np.sum(exp_x, axis=0, keepdims=True)
    return softmax_probs.T
def ReLU_deriv(Z):
    return Z > 0


In [30]:
# this whole cell is dedicated to initialized the weight,bias for layer no. 1 then get the output and sigmoid squishify the output

weight_layer1,bias_layer1 = weight_bias_make(100,784,4000)

unactivated_output1 = forward_prop(weight_layer1,images,bias_layer1)
neuron_output_layer1 = relu(unactivated_output1)
weight_layer1

array([[ 0.00023516,  0.02699222, -0.0090967 , ..., -0.00302514,
        -0.03234109,  0.00176173],
       [ 0.00065721,  0.0034122 ,  0.00240204, ..., -0.0097067 ,
        -0.00865509,  0.00213153],
       [-0.00528269, -0.00096745,  0.01509009, ..., -0.01077234,
        -0.00200033,  0.00890235],
       ...,
       [ 0.00738516,  0.01262531,  0.01455015, ..., -0.00442387,
        -0.00609068, -0.0025176 ],
       [-0.0046564 ,  0.00854843, -0.02968371, ..., -0.012809  ,
        -0.0052784 ,  0.00601058],
       [ 0.00964562, -0.00405026, -0.01866311, ..., -0.00980683,
        -0.00882485,  0.00973808]], shape=(100, 784))

In [31]:
# this whole cell is dedicated to initialized the weight,bias for layer no. 2 then get the output and sigmoid squishify the output
weight_layer2,bias_layer2 = weight_bias_make(10,100,4000)
unactivated_output2 = forward_prop(weight_layer2,neuron_output_layer1,bias_layer2)
neuron_output_layer2 = relu(unactivated_output2)
neuron_output_layer2

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00084017, 0.00127029, 0.00405801, ..., 0.0080764 , 0.01026426,
        0.00905033],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.00172293, ..., 0.00398835, 0.00057819,
        0.0068929 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.00155469,
        0.        ],
       [0.        , 0.000733  , 0.        , ..., 0.00615104, 0.01525094,
        0.        ]], shape=(10, 4000))

In [32]:
# this whole cell is dedicated to initialized the weight,bias for layer no. 3 then get the output and sigmoid squishify the output
weight_layer3,bias_layer3 =  weight_bias_make(5,10,4000)
unactivated_output3 = forward_prop(weight_layer3,neuron_output_layer2,bias_layer3)
print(unactivated_output3.shape)
neuron_output_layer3 = softmax(unactivated_output3) #softmax is being used,'''experimental ZZZZ '''
neuron_output_layer3

(5, 4000)


array([[0.20000034, 0.20000676, 0.19998436, 0.19999943, 0.20000911],
       [0.20000506, 0.20000391, 0.19998611, 0.19999515, 0.20000977],
       [0.19999992, 0.20000738, 0.19999817, 0.19999813, 0.1999964 ],
       ...,
       [0.2000166 , 0.20002022, 0.1999906 , 0.19999033, 0.19998226],
       [0.20004401, 0.20002728, 0.200011  , 0.19998213, 0.19993558],
       [0.19999732, 0.20001565, 0.19999191, 0.19999286, 0.20000227]],
      shape=(4000, 5))

In [33]:
root = os.listdir("/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Train")
list_clean(root)
classes = []
final_classes = []
for j in range(5):
    for i in range(800):
        classes.append(j)
    
    
classes = pd.DataFrame(classes)
classes = pd.get_dummies(classes,columns=[0])
classes = classes.astype(float)
classes = np.array(classes)
root
'''['James', 'Joel', 'Jovi', 'Jane', 'Jade']'''

"['James', 'Joel', 'Jovi', 'Jane', 'Jade']"

In [34]:
#this is an example of the implementation of the backward propagation from my yt teacher...
'''def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2'''

'def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):\n    one_hot_Y = one_hot(Y)\n    dZ2 = A2 - one_hot_Y\n    dW2 = 1 / m * dZ2.dot(A1.T)\n    db2 = 1 / m * np.sum(dZ2)\n    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)\n    dW1 = 1 / m * dZ1.dot(X.T)\n    db1 = 1 / m * np.sum(dZ1)\n    return dW1, db1, dW2, db2'

In [35]:
def back_prop(images,classes,pred3,pred2,pred1,rows,W1,W2,W3,unac_1,unac_2,unac_3):
    #lots of math wrote it while looking at the formulas on the internet, to understand this, have to read
    dZ3 = pred3 - classes
    
    dw3 = 1/rows * np.dot(dZ3.T,pred2.T)
    db3 = 1/rows * np.sum(np.sum(dZ3))
    dZ2 = np.dot(W3.T,dZ3.T) * ReLU_deriv(unac_2)
    dw2 = 1/rows * np.dot(dZ2,pred1.T)
    db2 = 1/rows * np.sum(dZ2)
    dZ1 = np.dot(W2.T,dZ2)* ReLU_deriv(unac_1)
    dw1 = 1/rows*np.dot(dZ1,images.T)
    db1 = 1/rows*np.sum(dZ1)
    
    return dw1,db1,dw2,db2,dw3,db3,dZ3
    
    

In [36]:
learning_rate = 0.1
for _ in range(1000):
    #this is pretty simple, it is calculating dot product each time loop goes off
    unactivated_output1 = forward_prop(weight_layer1,images,bias_layer1)
    neuron_output_layer1 = relu(unactivated_output1)
    unactivated_output2 = forward_prop(weight_layer2,neuron_output_layer1,bias_layer2)
    neuron_output_layer2 = relu(unactivated_output2)
    unactivated_output3 = forward_prop(weight_layer3,neuron_output_layer2,bias_layer3)
    neuron_output_layer3 = softmax(unactivated_output3)
    
    #here let's perform the back prop:::
    dw1,db1,dw2,db2,dw3,db3,dZ3=back_prop(images,classes,neuron_output_layer3,neuron_output_layer2,neuron_output_layer1,4000,weight_layer1,weight_layer2,weight_layer3,unactivated_output1,unactivated_output2,unactivated_output3)
    weight_layer1 -= learning_rate*dw1
    weight_layer2 -= learning_rate*dw2
    weight_layer3 -= learning_rate*dw3
    bias_layer1 -= learning_rate*db1
    bias_layer2 -= learning_rate*db2
    bias_layer3 -= learning_rate*db3
    if _%100== 0:
        print(dZ3)
        print("*"*80)
    warnings.filterwarnings("ignore", category=FutureWarning)
    

[[-0.79999966  0.20000676  0.19998436  0.19999943  0.20000911]
 [-0.79999494  0.20000391  0.19998611  0.19999515  0.20000977]
 [-0.80000008  0.20000738  0.19999817  0.19999813  0.1999964 ]
 ...
 [ 0.2000166   0.20002022  0.1999906   0.19999033 -0.80001774]
 [ 0.20004401  0.20002728  0.200011    0.19998213 -0.80006442]
 [ 0.19999732  0.20001565  0.19999191  0.19999286 -0.79999773]]
********************************************************************************
[[-0.799997    0.20004681  0.19990103  0.19996495  0.20008421]
 [-0.79999196  0.20004687  0.19990785  0.19996158  0.20007567]
 [-0.7999999   0.20004067  0.1999131   0.19996295  0.20008318]
 ...
 [ 0.19999209  0.20005845  0.19984254  0.19993572 -0.79982881]
 [ 0.20000462  0.20006005  0.19985611  0.19995177 -0.79987255]
 [ 0.19996026  0.20005206  0.19984225  0.19994102 -0.79979559]]
********************************************************************************
[[-0.8001814   0.20007992  0.19952479  0.19966886  0.20090782]
 [-0.80

In [37]:
def reverse_softmax(probabilities):
    # Add a small constant to avoid log(0)
    epsilon = 1e-12
    probabilities = np.clip(probabilities, epsilon, 1 - epsilon)
    
    # Compute logits
    logits = np.log(probabilities)
    logits -= np.max(logits, axis=-1, keepdims=True)  # Adjust for stability (optional)
    
    return logits

In [38]:
def get_accuracy(predictions, Y):
    no = np.sum(predictions != Y)
    yes = np.sum(predictions == Y)
    return yes/(yes + no)
    

In [39]:


result = reverse_softmax(neuron_output_layer3)
result = pd.DataFrame(result)

result[0] = result[0].map({0:1})
result[1] = result[1].map({0:1})
result[2] = result[2].map({0:1})
result[3] = result[3].map({0:1})
result[4] = result[4].map({0:1})
result = result.fillna(0)
result = np.array(result)
print("Accuracy:", float(get_accuracy(result,classes)*100),"%")


Accuracy: 98.3 %


In [40]:
Neural_network_folder = os.listdir("/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK")

# THis function down below clear the .DS_Store file which is specific to mac_os   
# wherever this function is called, it is just to remove that .DS_Store file of mac
def list_clean(L):
    for i in L:
        if i ==".DS_Store":
            L.remove(i)

list_clean(Neural_network_folder)

#This code below is supposed to get the names of the folder inside the neural_network/ folder
Names_folder_test = os.listdir(f"/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Test")
list_clean(Names_folder_test)

images_path = [] # as the name suggests, it stores the path of each of the image and stuff
images_test = []# to store each of the image information of all the folders ....

for i in Names_folder_test:
    list_clean(images_path)
    images_path= os.listdir(f"/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Test/{i}")
    
    #Loop for storing the image info into the List
    for j in images_path:
        img = cam.imread(f"/Users/pragyandas/Desktop/ML_Practice/NEURAL_NETWORK/Test/{i}/{j}",cam.IMREAD_GRAYSCALE)
        images_test.append(img.flatten())
    


# convert the list into array for vector operations
images_test = np.array(images_test)

'''['James', 'Joel', 'Jovi', 'Jane', 'Jade']'''
Names_folder_test

['James', 'Joel', 'Jovi', 'Jane', 'Jade']

In [41]:
'''def model(weight_layer1,weight_layer2,weight_layer3,bias_layer1,bias_layer2,bias_layer3,image_to_test):
    unactivated_output1_test = forward_prop(weight_layer1,images_to_test,bias_layer1)
    neuron_output_layer1_test = relu(unactivated_output1_test)
    unactivated_output2_test = forward_prop(weight_layer2,neuron_output_layer1_test,bias_layer2)
    neuron_output_layer2_test = relu(unactivated_output2)
    unactivated_output3_test = forward_prop(weight_layer3,neuron_output_layer2_test,bias_layer3)
    neuron_output_layer3_test = softmax(unactivated_output3_test)'''

'def model(weight_layer1,weight_layer2,weight_layer3,bias_layer1,bias_layer2,bias_layer3,image_to_test):\n    unactivated_output1_test = forward_prop(weight_layer1,images_to_test,bias_layer1)\n    neuron_output_layer1_test = relu(unactivated_output1_test)\n    unactivated_output2_test = forward_prop(weight_layer2,neuron_output_layer1_test,bias_layer2)\n    neuron_output_layer2_test = relu(unactivated_output2)\n    unactivated_output3_test = forward_prop(weight_layer3,neuron_output_layer2_test,bias_layer3)\n    neuron_output_layer3_test = softmax(unactivated_output3_test)'

In [42]:
images_test = images_test/255 #this is to scale down the images and the info more centered
images_test = images_test.T
images_test.shape


(784, 1000)

In [43]:
unactivated_output1_test = forward_prop(weight_layer1,images_test,bias_layer1)
print(weight_layer1.shape)
neuron_output_layer1_test = relu(unactivated_output1_test)
unactivated_output2_test = forward_prop(weight_layer2,neuron_output_layer1_test,bias_layer2)
print(weight_layer2.shape)
neuron_output_layer2_test = relu(unactivated_output2_test)

unactivated_output3_test = np.dot(weight_layer3,neuron_output_layer2_test)+ bias_layer3
neuron_output_layer3_test = softmax(unactivated_output3_test)
neuron_output_layer2_test.shape

(100, 784)
(10, 100)


(10, 1000)

In [44]:
test_result=[]
for j in range(5):
    for i in range(200):
        test_result.append(j)
    
    
test_result = pd.DataFrame(test_result)
test_result = pd.get_dummies(test_result,columns=[0])
test_result = test_result.astype(float)
test_result = np.array(test_result)
test_result

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]], shape=(1000, 5))

In [45]:
result_test = reverse_softmax(neuron_output_layer3_test)
result_test = pd.DataFrame(result_test)

result_test[0] = result_test[0].map({0:1})
result_test[1] = result_test[1].map({0:1})
result_test[2] = result_test[2].map({0:1})
result_test[3] = result_test[3].map({0:1})
result_test[4] = result_test[4].map({0:1})
result_test = result_test.fillna(0)
result_test = np.array(result_test)
result_test.shape
print("Accuracy:", float(get_accuracy(result_test,test_result)*100),"%")


Accuracy: 98.32 %


### ******TEST ACCURACY AROUND 94 to 95 percent and around 92 percent FOR TRAINING DATA AS WELL*******
### THIS IS WITHOUT ANY EXTRA OPTIMIZATION TECHNIQUES OR BATCH TRAINING METHOD

In [46]:
#had made a smaller batch of test data in a new folder which had 150 pictures, 30 pic of each type
#deleted it mistakenly, nevermind!
'''Neural_network_folder_test2= os.listdir("/Users/pragyandas/Desktop/test_folder")

# THis function down below clear the .DS_Store file which is specific to mac_os   
# wherever this function is called, it is just to remove that .DS_Store file of mac
def list_clean(L):
    for i in L:
        if i ==".DS_Store":
            L.remove(i)

list_clean(Neural_network_folder)

#This code below is supposed to get the names of the folder inside the neural_network/ folder
Names_folder_test2 = os.listdir(f"/Users/pragyandas/Desktop/test_folder")
list_clean(Names_folder_test2)

 # as the name suggests, it stores the path of each of the image and stuff
images_test = []# to store each of the image information of all the folders ....
list_clean(images_path)
for i in Names_folder_test2:
    
    images_path= os.listdir(f"/Users/pragyandas/Desktop/test_folder/{i}")
    list_clean['James', 'Joel', 'Jovi', 'Jane', 'Jade'](images_path)
    #Loop for storing the image info into the List
    for j in images_path:
        img = cam.imread(f"/Users/pragyandas/Desktop/test_folder/{i}/{j}",cam.IMREAD_GRAYSCALE)
        if img is None:
            continue
        else:
            images_test.append(img.flatten())
    


# convert the list into array for vector operations
images_test = np.array(images_test)


images_test = images_test.T
images_test = images_test/255
'''

'Neural_network_folder_test2= os.listdir("/Users/pragyandas/Desktop/test_folder")\n\n# THis function down below clear the .DS_Store file which is specific to mac_os   \n# wherever this function is called, it is just to remove that .DS_Store file of mac\ndef list_clean(L):\n    for i in L:\n        if i ==".DS_Store":\n            L.remove(i)\n\nlist_clean(Neural_network_folder)\n\n#This code below is supposed to get the names of the folder inside the neural_network/ folder\nNames_folder_test2 = os.listdir(f"/Users/pragyandas/Desktop/test_folder")\nlist_clean(Names_folder_test2)\n\n # as the name suggests, it stores the path of each of the image and stuff\nimages_test = []# to store each of the image information of all the folders ....\nlist_clean(images_path)\nfor i in Names_folder_test2:\n    \n    images_path= os.listdir(f"/Users/pragyandas/Desktop/test_folder/{i}")\n    list_clean[\'James\', \'Joel\', \'Jovi\', \'Jane\', \'Jade\'](images_path)\n    #Loop for storing the image info i

In [77]:
# this is function to simplify things and make a "do it all" function and I made it at the very end so, didn't use it before
def model(weight_layer1,weight_layer2,weight_layer3,bias_layer1,bias_layer2,bias_layer3,images_to_test_list):
    unactivated_output1_test2 = forward_prop(weight_layer1,images_to_test_list,bias_layer1)
    neuron_output_layer1_test2 = relu(unactivated_output1_test2)
    unactivated_output2_test2 = forward_prop(weight_layer2,neuron_output_layer1_test2,bias_layer2)
    neuron_output_layer2_test2 = relu(unactivated_output2_test2)
    unactivated_output3_test2 = forward_prop(weight_layer3,neuron_output_layer2_test2,bias_layer3)
    neuron_output_layer3_test2 = softmax(unactivated_output3_test2)
    result_test = reverse_softmax(neuron_output_layer3_test2)
    result_test = pd.DataFrame(result_test)

    result_test[0] = result_test[0].map({0:1})
    result_test[1] = result_test[1].map({0:1})
    result_test[2] = result_test[2].map({0:1})
    result_test[3] = result_test[3].map({0:1})
    result_test[4] = result_test[4].map({0:1})
    result_test = result_test.fillna(0)
    result_test = np.array(result_test)
    print("HELLO CREATOR, MY SORTING IS.....THAT IT")
    if result_test[0][0]==1:
        print('Belongs to James')
    if result_test[0][1]==1:
        print('Belongs to Joel')
    if result_test[0][2]==1:
        print('Belongs to Jovi')
    if result_test[0][3]==1:
        print('Belongs to Jane')
    if result_test[0][4]==1:
        print('Belongs to Jade')
    #return result_test
img_go = cam.imread(f"/Users/pragyandas/Desktop/test_folder/jl665.png",cam.IMREAD_GRAYSCALE)
img_go_list=[]
img_go_list.append(img_go.flatten())
img_go_list = np.array(img_go_list)
img_go_list=img_go_list/255
img_go_list = img_go_list.T

In [78]:
model(weight_layer1,weight_layer2,weight_layer3,bias_layer1,bias_layer2,bias_layer3,img_go_list)

HELLO CREATOR, MY SORTING IS.....THAT IT
Belongs to Joel
